spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargoDelivery?createDatabaseIfNotExist=TRUE&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:

    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Cargo Delivery Application
    description: This cargo delivery application helps to teleport your parcels to any place, where we have our offices
    owner:
      company: Cargo Delivery corp.
      headquarters: Lviv
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}
