spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargo-delivery?createDatabaseIfNotExist=TRUE&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:

    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
